fix: change port in sg for test v0.6

diff --git a/.github/workflows/terraform.yml b/.github/workflows/terraform.yml
--- a/.github/workflows/terraform.yml
+++ b/.github/workflows/terraform.yml
@@ -144,18 +144,19 @@ jobs:
           echo "Modified files:"
           git diff --name-only HEAD^ HEAD || echo "No differences"
 
-      - name: Download Plan Artifact
-        uses: actions/download-artifact@v4
-        with:
-          name: terraform-plan-${{ matrix.dir }}
-          path: terraform/${{ matrix.dir }}
+#      - name: Download Plan Artifact
+#        uses: actions/download-artifact@v4
+#        with:
+#          name: terraform-plan-${{ matrix.dir }}
+#          path: terraform/${{ matrix.dir }}
 
-      - name: Verify Plan Exists
-        run: |
-          if [ ! -f tfplan ]; then
-            echo "::error::Terraform plan file not found!"
-            exit 1
-          fi
+#      - name: Verify Plan Exists
+#        run: |
+#          if [ ! -f tfplan ]; then
+#            echo "::error::Terraform plan file not found!"
+#            exit 1
+#          fi
+
       - name: Setup Terraform
         uses: hashicorp/setup-terraform@v2
         with:
@@ -163,6 +164,10 @@ jobs:
 
       - name: Terraform Init
         run: terraform init -backend-config="bucket=${{ secrets.BUCKET_TF_STATE }}"
+
+      - name: Terraform Plan (New)
+        run: |
+          terraform plan -no-color -input=false -out=tfplan -var-file=../terraform.tfvars
 
       - name: Terraform Apply
         run: terraform apply -auto-approve tfplan
